### PR TITLE
Updated state.json

### PR DESCRIPTION
**Pull request by UtkarshGpta**
Removed incorrect states in the list.

### CODE REVIEW

**Comment by UtkarshGpta** [comment]
Hello, please update the npm package too, it's being used in one of the projects.

**Comment by UtkarshGpta** [comment]
Created a PR in the GitHub project from which this data has been taken.
[https://github.com/hiiamrohit/Countries-States-Cities-database/pull/94](Pull Request)

**Comment by UtkarshGpta** [comment]
> Created a PR in the GitHub project from which this data has been taken.
> [https://github.com/[hiiamrohit/Countries-States-Cities-database/pull/94](https://github.com/hiiamrohit/Countries-States-Cities-database/pull/94)](Pull Request)

Data repository has been updated, please take the latest data and update npm package.

**Comment by dz14** [comment]
Can someone please merge this PR?

**Pull request merged**
