### PR TITLE
Switch to classes and ES6/esmodule TS compilation

### PR DESCRIPTION
**Pull request by taylorthurlow**
I'm not 100% sure if this PR is welcome - this is obviously a big rewrite/refactor of how this is all structured, and will break every existing app that uses this library. So, no hard feelings if this gets closed, I mostly did this because I'm using this in a web app, and the size of the gzipped bundle when this library is included is WAY too high (2.6mb gzipped).

This is a rewrite which moves the primary Country, State, and City interfaces into their own classes. Each class has appropriate class and instance methods which replicate the existing functionality of the library, but in a way which allows full tree-shaking when one or more classes are not used in the dependent application.

In order to support tree-shaking, I had to change the TypeScript compiler options to generate ES6 compatible modules rather than CommonJS modules, and I'm not really an expert on JS in general, so I don't know what the implications are of that change as far as compatibility. I know that this should be fine for web applications, and I believe newer versions of Node will be fine with ES modules.

I'm still playing around with this, and I haven't updated the tests yet, so I'm marking this as a draft. Let me know if there is any interest in merging this.

Thanks!

### CODE REVIEW

**Comment by harpreetkhalsagtbit** [comment]
@taylorthurlow Thanks for your effort. Your concerns are right but I hope it won't go waste.

**Comment by harpreetkhalsagtbit** [comment]
@taylorthurlow updated the base branch - I will review and test it further.

**Comment by taylorthurlow** [comment]
Thanks for taking a look! I just rewrote the tests and pushed everything up. I have 100% coverage but there is some weirdness with the branch coverage percentage on `src/city.ts`, which I can't figure out.

**Comment by harpreetkhalsagtbit** [comment]
@taylorthurlow your code is already refactored and merged into the develop branch.

**Comment by taylorthurlow** [comment]
> @taylorthurlow your code is already refactored and merged into the develop branch.

Thanks! Sorry I've been busy. Will get to this sometime next week I think.

**Pull request closed without merging**
