### PR TITLE
update Antarctica phone code

### PR DESCRIPTION
**Pull request by OozyGrub**

### CODE REVIEW

**Comment by harpreetkhalsagtbit** [comment]
@dr5hn can you please review this.

**Comment by dr5hn** [comment]
@harpreetkhalsagtbit This has been already updated in my database. I will raise a PR with updated json files soon.

**Comment by harpreetkhalsagtbit** [comment]
I have updated the package and you have to update the PR accordingly.

**Comment by dr5hn** [comment]
@harpreetkhalsagtbit Done.

**Comment by harpreetkhalsagtbit** [comment]
@OozyGrub this change has been added into the main codebase by some other PR. Sorry for the delay and Thanks for the effort.

**Pull request closed without merging**
