### PR TITLE
add rivers state

### PR DESCRIPTION
**Pull request by radiumrasheed**

### CODE REVIEW

**Comment by harpreetkhalsagtbit** [comment]
@dr5hn can you please review this...

**Comment by dr5hn** [comment]
@harpreetkhalsagtbit This has been already updated in my database. I will raise a PR with updated json files soon.

**Comment by radiumrasheed** [comment]
@dr5hn you can close my PR once that is merged in right?

**Comment by dr5hn** [comment]
@radiumrasheed Yes

**Comment by dr5hn** [comment]
@harpreetkhalsagtbit 
Please merge this #75

**Comment by harpreetkhalsagtbit** [comment]
I have updated the package and you have to update the PR accordingly.

**Comment by dr5hn** [comment]
@harpreetkhalsagtbit Done.

**Pull request closed without merging**
